config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :animals, only: [:new, :create, :index]
  resources :medications
  root "home#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :paws
  has_many :hoofs
  accepts_nested_attributes_for :hoofs

  validates_length_of :hoofs, maximum: 4, message: "Less than 5 paws!"
  validates_length_of :paws, maximum: 4, message: "Less than 5 paws!"


  def hoof
    hoofs.first
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hoof.rb
class Hoof < ApplicationRecord
  belongs_to :animal
end

app/models/lesion.rb
class Lesion < ApplicationRecord
  # belongs_to :session, foreign_key: "session_id"
end

app/models/medication.rb
class Medication < ApplicationRecord
end

app/models/paw.rb
class Paw < ApplicationRecord
  has_many :sessions
  belongs_to :animal, foreign_key: "animal_id"

end

app/models/session.rb
class Session < ApplicationRecord
  has_many :lesions
  # belongs_to :paw, foreign_key: "paw_id"
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end
  def new
    @animal = Animal.new
    @animal.hoofs.build
  end

  def create
    @animal = Animal.new animal_params
    if @animal.save
      redirect_to root_path
    else
      render action: :new
    end
  end
  private
  def animal_params
    params.require(:animal).permit(:identificacao, :lote, :escore, hoofs_attributes:
      [:a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9, :a10, :a11, :a12, :a13, :a14, :a15, :a16, :a17, :a18])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  def new
    @medication = Medication.new
  end

  def create
    redirect_to root_url
  end

end

app/controllers/paws_controller.rb
class PawsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/paws_helper.rb
module PawsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/animals/_form.html.erb
<% if @animal.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@animal.errors.count, "error") %>.
    </div>
    <ul>
    <% @animal.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @animal do |f| %>
  <div class="form-group">
    <%= f.label :identificacao %>
    <%= f.text_field :identificacao, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :lote %>
    <%= f.text_field :lote, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :escore %>
    <%= f.text_field :escore, class: "form-control" %>
  </div>

  <%= f.fields_for :hoofs do |h| %>
  <div class="hidden">
    <label class="form-check-label">
      <%= h.label :"Area 1" %>
      <%= h.check_box :a1 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>

    <label class="form-check-label">
      <%= h.label :"Area 2" %>
      <%= h.check_box :a2 %>
    </label>

    <label class="form-check-label">
      <%= h.label :"Area 3" %>
      <%= h.check_box :a3 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>

    <label class="form-check-label">
      <%= h.label :"Area 4" %>
      <%= h.check_box :a4 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 5" %>
      <%= h.check_box :a5 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 6" %>
      <%= h.check_box :a6 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 7" %>
      <%= h.check_box :a7 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 8" %>
      <%= h.check_box :a8 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 9" %>
      <%= h.check_box :a9 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 10" %>
      <%= h.check_box :a10 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 11" %>
      <%= h.check_box :a11 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 12" %>
      <%= h.check_box :a12 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 13" %>
      <%= h.check_box :a13 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 14" %>
      <%= h.check_box :a14 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 15" %>
      <%= h.check_box :a15 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 16" %>
      <%= h.check_box :a16 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 17" %>
      <%= h.check_box :a17 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>
    <label class="form-check-label">
      <%= h.label :"Area 18" %>
      <%= h.check_box :a18 %>
      <!-- <input class="form-check-input" type="checkbox" id="area0" value="option1"> Area 0 -->
    </label>    
  </div>
  <% end %>

  <%= render "paw" %>
  <div class="form-group">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/animals/index.html.erb
<% @animals.each do |animal| %>
  <%= render "paw_item", animal: animal %>
<% end %>

app/views/animals/new.html.erb
<h2>Casqueamento</h2>
<%= render "form" %>

app/views/layouts/_content_header.html.erb
<section class="content-header">
	<h1>Dashboard <small><%= title_header %></small></h1>
	<ol class="breadcrumb">
		<% path.each do |pat| %>
			<li><a href="#"><%= pat %></a></li>
		<% end %>
	</ol>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container-fluid bg-inverse py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <div class="row py-0">
            <div class="col-sm-1 hidden-md-down">
              <a class="bg-circle bg-info" href="#">
                <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
              </a>
            </div>
            <div class="col-sm-11 text-white">
              <div>
                <h4>Entre em contato:</h4>
                <p>
                  <span class="header-font"></span>
                  <span class="header-font"></span>
                  (85) 988156415</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-5">
          <div class="d-inline-block">
            <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
              <a href="https://www.facebook.com/">
                <i class="fa fa-2x fa-fw fa-facebook text-white"></i>
              </a>
            </div>
            <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
              <a href="https://www.linkedin.com/company/">
                <i class="fa fa-2x fa-fw fa-linkedin text-white"></i>
              </a>
            </div>
            <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
              <a href="https://www.google.com/">
                <i class="fa fa-2x fa-fw fa-google text-white"></i>
              </a>
            </div>
          </div>
        </div>
        <p class="text-center text-white"> Copyright © Acens Empresa Júnior. Todos os direitos reservados. </p>

      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="main-header">
    <!-- Logo -->
    <%= link_to root_path, class: "logo" do %>
      <span class="logo-mini">D.M.</span>
      <span class="logo-lg">Demo <i class="fa fa-paw"></i></span>
    <% end %>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Notifications: style can be found in dropdown.less -->
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag "img.jpg", class: "user-image", alt: "User image" %>
              <span class="hidden-xs">Alexandra Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <%= image_tag "img.jpg", class: "user-image", alt: "User image" %>

                <p>
                  Alexandra Pierce - Admin
                  <small>Member since Nov. 2017</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Editar Perfil</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">None</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">None</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <%= image_tag "img.jpg", class: "user-image img-circle", alt: "User image" %>
        </div>
        <div class="pull-left info">
          <p>Alexandra Pierce</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-group"></i> <span>Usuários</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li class="active">
            <%= link_to root_path do %>
              <i class="fa fa-user-o"></i>Novo usuário
            <% end %>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i>Histórico</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-book"></i> <span>Casqueamento</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li>
              <%= link_to new_animal_path do %>
                <i class="fa fa-circle-o"></i>Novo Animal
              <% end %>
            </li>
            <li>
              <%= link_to animals_path do %>
                <i class="fa fa-circle-o"></i>Lista de animais
              <% end %>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i>Lista de animais</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-book"></i> <span>Medicação</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-circle-o"></i>Novo Medicamento
              <% end %>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i>Lista de Medicamentos</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i>Custo</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i>Estoque</a></li>
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/_statistics.html.erb
<div class="row">
	<div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-green">
        <div class="inner">
          <h3><%= 3 %></h3>
<!--           <h3>53<sup style="font-size: 20px">%</sup></h3> -->

          <p>Semana passada</p>
        </div>
        <div class="icon">
          <i class="fa fa-calendar"></i>
        </div>
        <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
   	<div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3><%= 2 %></h3>
<!--           <h3>53<sup style="font-size: 20px">%</sup></h3> -->

          <p>Hoje</p>
        </div>
        <div class="icon">
          <i class="fa fa-shopping-bag"></i>
        </div>
        <a href="#" class="small-box-footer">Mais informações <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Casqueamento - MVP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': 'false' %>
    <%= favicon_link_tag 'cow.ico', rel: 'apple-touch-icon' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="img/cow.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="skin-blue sidebar-mini wysihtml5-supported">

    <body class="skin-blue sidebar-mini wysihtml5-supported">
      <div class="wrapper">
        <!--navbar -->
        <%= render 'layouts/navbar' %>
        <!-- end navbar -->
        <!-- sidebar -->
        <%= render 'layouts/sidebar' %>
        <!-- end sidebar -->
        <!-- container -->
        <div class="content-wrapper">
          <%= render 'layouts/content_header', title_header: "Painel de controle", path: ["Home", "Dashboard"] %>
          <section class="content">
            <% if flash[:alert] %>
              <div class="alert alert-success"><%= flash[:alert] %></div>
            <% end %>
            <%= render 'layouts/statistics'%>
            <%= yield %>
          </section>

        </div>
        <!-- end container -->

      </div>
    </body>
  </html>

app/views/logins/logins.html.erb
<!-- BEGIN # BOOTSNIP INFO -->
<div class="container">
	<div class="row">
		<br><br><br>
		<center><h1 class="text-center text-white">Registre e Gere Relatórios de Casqueamento de Forma Rápida</h1></center><br><br>
        <center><p class="text-center"><a href="#" class="btn btn-primary btn-lg" role="button" data-toggle="modal" data-target="#login-modal">Acessar Conta da Fazenda</a></p></center>
				<br><br><br><br><br><br><br><br><br><br>

	</div>
</div>
<!-- END # BOOTSNIP INFO -->

<!-- BEGIN # MODAL LOGIN -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    	<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header" align="center">
					<img class="img-circle" id="img_logo" src="https://image.flaticon.com/icons/svg/58/58777.svg">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
					</button>
				</div>

                <!-- Begin # DIV Form -->
                <div id="div-forms">

                    <!-- Begin # Login Form -->
                    <form id="login-form">
		                <div class="modal-body">
				    		<div id="div-login-msg">
                                <div id="icon-login-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-login-msg">Insira seu usuário e senha.</span>
                            </div>
				    		<input id="login_username" class="form-control" type="text" placeholder="Digite seu nome de usuário" required>
				    		<input id="login_password" class="form-control" type="password" placeholder="Digite sua senha" required>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Lembre-se de mim
                                </label>
                            </div>
        		    	</div>
				        <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                            </div>
				    	    <div>
                                <button id="login_lost_btn" type="button" class="btn btn-link">Esqueceu sua senha?</button>
                                <button id="login_register_btn" type="button" class="btn btn-link">Registre-se</button>
                            </div>
				        </div>
                    </form>
                    <!-- End # Login Form -->

                    <!-- Begin | Lost Password Form -->
                    <form id="lost-form" style="display:none;">
    	    		    <div class="modal-body">
		    				<div id="div-lost-msg">
                                <div id="icon-lost-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-lost-msg">Digite seu email</span>
                            </div>
		    				<input id="lost_email" class="form-control" type="text" placeholder="Digite seu email" required>
            			</div>
		    		    <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Entrar</button>
                            </div>
                            <div>
                                <button id="lost_login_btn" type="button" class="btn btn-link">Log In</button>
                                <button id="lost_register_btn" type="button" class="btn btn-link">Registrar Fazenda</button>
                            </div>
		    		    </div>
                    </form>
                    <!-- End | Lost Password Form -->

                    <!-- Begin | Register Form -->
                    <form id="register-form" style="display:none;">
            		    <div class="modal-body">
		    				<div id="div-register-msg">
                                <div id="icon-register-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-register-msg">Registre sua Fazenda.</span>
                            </div>
		    				<input id="register_username" class="form-control" type="text" placeholder="Digite seu nome de usuário" required>
                            <input id="register_email" class="form-control" type="text" placeholder="Digite seu email" required>
                            <input id="register_password" class="form-control" type="password" placeholder="Digite sua senha" required>
            			</div>
		    		    <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Registrar</button>
                            </div>
                            <div>
                                <button id="register_login_btn" type="button" class="btn btn-link">Log In</button>
                                <button id="register_lost_btn" type="button" class="btn btn-link">Esqueceu sua senha?</button>
                            </div>
		    		    </div>
                    </form>
                    <!-- End | Register Form -->
                </div>
                <!-- End # DIV Form -->

			</div>
		</div>
	</div>
    <!-- END # MODAL LOGIN -->

app/views/medications/new.html.erb
<%= form_for @medication do |f| %>
<%= f.label :nome %>
<%= f.text_field :nome %>

<%= f.label :qtd_dose %>
<%= f.number_field :qtd_dose %>

<%= f.label :dias_aplicacao %>
<%= f.text_field :dias_aplicacao %>

<%= f.submit "Enviar" %>

<% end %>